
input_str = "CTGTCTCGAGGAATAGGAGAGCGGGAACTATCCCCGTTCGTATTGATTGTAAGCTCACTGACGCCGGTGTGGGGGGATAGCAGCTCTCTTCTGCAGGGCTGAGACCGCACGTTCGTTGTCCTTTAAAGGCCACCCGGCGAGTCTTCATCGACTGCGCGGCTCTCATACGCGCTCACTCGACGGCACGTGTCCACGTCATAGTGCAACCAAGTTCTAGTTTATAGGTGCGTAACGCCAAGCTCATTATAGTAGTACGGATCTCGCGGGTGGGGTTTAGCACGTGTAATACAATGCAGTAATATAAATCTTTCGAATCCATGGGTATCTCGGTGCCCCGATATGGGCAGCTTCCTATGAATAGCGCTTATTCGTGGTTCTGAAGTTTCCTCACATAAGTTCAGCCTCCCATGTAAAACGTGCGCAGCTGTCATAACCCTCTAGTGTGTGACACGCCTGGGGCCGCGCGGGTGTCCCCCGTCTAGCAATTTTCATACGTTAAGCACCGGAAGGCCTGGTATGGCGAGGAGGATAGAAGTTCGGCTTCTAGATCCCGCTTCCGAGGTTAGCTACGTTGACGGGGGCTCGCCGGTCAGAATCCCCATCTACTAGCTACGACATGCGGTAGCTATTCGCTGTCGTCGGCCTTCTATCCGTAAATTGATAGCCGTAGGGGAAAATCGGGTCTTGTGCGCTACTCGAACTCGTGAGAATCAAGCTGTCGGTCTGCATAACTCTATTGCGGAAGGTTCCCTCACCATTTCCTCTCGTGCTGGTGTGACCACTTGATTAGCAAGTTTGCGCAACGGCATGGCACTGGAAAAGCCGGTAGTTTGGAATTAACACCGAGCTGACTCTTAAACGCACCAGCTAAAGACATGGCCGGTAAAAACCACATCAACGTTCACTCGCTCGCCCCTGCATCCACATCGTAATTGATTGATATGTACTGGCATTATGAGTCGTTTGGAGAACGG"

complement = []

for letter in input_str:
    if letter == 'C':
        complement.append('G')
    elif letter == 'G':
        complement.append('C')
    elif letter == 'A':
        complement.append('T')
    elif letter == 'T':
        complement.append('A')
    else:
        complement.append(letter)

my_str = ''.join(str(x) for x in reversed(complement))

print(my_str)
# my_str = ''.join(str(x) for x in reverse_complement)
# print(my_str)